### PR TITLE
Modify spec to support RHEL 6 environment

### PR DESCRIPTION
**Pull request by bocekm**
Signed-off-by: Michal Bocek <mbocek@redhat.com>

### CODE REVIEW

**Comment by bmr-cymru** [comment]
Thanks @bocekm - I've found some bugs running boom on RHEL6 that I'd not spotted before. I'm hoping that I can get them fixed up today/tomorrow and I'll merge this as soon as it's running.

**Comment by bocekm** [comment]
Yeah, as RHEL uses Python 2.6 a few syntax constructs would need to be updated. At least the dict generator:
`SyntaxError: ('invalid syntax', ('/usr/lib/python2.6/site-packages/boom/bootloader.py', 110, 19, 'MAP_KEY = {v: k for k, v in KEY_MAP.items()}\n'))`

Regardless of this syntax error, the package gets created with this PR.

**Comment by bmr-cymru** [comment]
Yep: I have a simple fix for that locally:

```python
def __make_map_key(key_map):
    """Compatibility function to generate a reverse dictionary on
        Python 2.6 which does not support dictionary comprehension
        notation.
    """
    map_key = {}
    for k, v in key_map.items():
        map_key[v] = k
    return map_key


#: Map BLS entry keys to Boom names
MAP_KEY = __make_map_key(KEY_MAP)
#MAP_KEY = {v: k for k, v in KEY_MAP.items()}
```

There also seems to be a change in `super()` syntax that I am looking at now (I last tested this on RHEL6 last year before some of these changes landed), as well as Dracut syntax changes that I was aware of but had forgotten about.

They all seem fairly simple (although the `super()` thing might end up with a downstream patch: just depends how ugly the final solution ends up looking).

**Comment by bmr-cymru** [comment]
I've merged this and the sphinx change now - thanks again for your help.

I've pushed a few other fixes to master, and also a new branch `bmr-py26` which has the workaround for the lack of dict comprehension in 2.6: I'll see whether we accumulate more of these before deciding whether to merge that or to keep it RHEL6 specific.

I can build RPMs in mock from the 2.6 branch now and at least basic functionality is working:

```
[root@localhost boom]# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.8 (Santiago)
[root@localhost boom]# rpm -q python-boom
python-boom-0.8-1.el6.noarch
[root@localhost boom]# boom create --title TEST --root-device /dev/VolGroup/lv_root
WARNING - No Grub2 configuration file found
WARNING - Boom configuration not found in grub.cfg
WARNING - Run 'grub2-mkconfig > /boot/grub2/grub.cfg' to enable
Created entry with boot_id d745bfd:
  title TEST
  machine-id 5101b1a4e4237dfc86de2ce300000006
  version 2.6.32-642.el6.x86_64
  linux /vmlinuz-2.6.32-642.el6.x86_64
  initrd /initramfs-2.6.32-642.el6.x86_64.img
  options root=/dev/VolGroup/lv_root ro rd.lvm.lv=VolGroup/lv_root rhgb quiet
[root@localhost boom]# boom list
BootID  Version                  Name                            RootDevice           
d745bfd 2.6.32-642.el6.x86_64    Red Hat Enterprise Linux Server /dev/VolGroup/lv_root
[root@localhost boom]# boom delete --bootid d745bfd
Deleted 1 entry
```

**Pull request closed without merging**
